import { MenuItem } from './types';

export const MENU_ITEMS: MenuItem[] = [
  {
    id: '1',
    name: 'Truffle Scallops',
    description: 'Hokkaido scallops, black truffle shavings, cauliflower purée.',
    price: 32,
    category: 'Appetizers',
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&q=80&w=800',
    nutritionalInfo: { calories: 240, protein: '18g', fat: '12g' },
    allergens: ['Shellfish', 'Dairy'],
    isGlutenFree: true,
    ingredients: [
      { name: 'Sea Scallops', origin: 'Hokkaido, Japan' },
      { name: 'Black Truffle', origin: 'Perigord, France' },
      { name: 'Cauliflower', origin: 'Local Organic Farms' }
    ],
  },
  {
    id: '2',
    name: 'Wagyu A5 Striploin',
    description: 'Miyazaki Wagyu, aged balsamic reduction, roasted bone marrow.',
    price: 125,
    category: 'Mains',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&q=80&w=800',
    nutritionalInfo: { calories: 680, protein: '42g', fat: '54g' },
    allergens: ['Beef'],
    isGlutenFree: true,
    ingredients: [
      { name: 'Wagyu Beef', origin: 'Miyazaki Prefecture, Japan' },
      { name: 'Balsamic Vinegar', origin: 'Modena, Italy' },
      { name: 'Bone Marrow', origin: 'Premium Grass-fed Beef' }
    ],
  },
  {
    id: '3',
    name: 'Wild Mushroom Risotto',
    description: 'Arborio rice, porcini, chanterelles, 24-month aged parmesan.',
    price: 45,
    category: 'Mains',
    image: 'https://images.unsplash.com/photo-1476124369491-e7addf5db371?auto=format&fit=crop&q=80&w=800',
    nutritionalInfo: { calories: 520, protein: '14g', fat: '22g' },
    allergens: ['Dairy', 'Mushrooms'],
    isVegetarian: true,
    isGlutenFree: true,
  },
  {
    id: '4',
    name: 'Gold Leaf Chocolate Dome',
    description: 'Valrhona chocolate, salted caramel heart, 24k gold leaf.',
    price: 28,
    category: 'Desserts',
    image: 'https://images.unsplash.com/photo-1551024601-bec78aea704b?auto=format&fit=crop&q=80&w=800',
    nutritionalInfo: { calories: 410, protein: '6g', fat: '28g' },
    allergens: ['Dairy', 'Soy'],
    isVegetarian: true,
    isGlutenFree: true,
  },
  {
    id: '5',
    name: 'Vintage Negroni',
    description: 'Small batch gin, 1970s Campari, house vermouth.',
    price: 24,
    category: 'Drinks',
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&q=80&w=800',
    nutritionalInfo: { calories: 190, protein: '0g', fat: '0g' },
    allergens: ['Alcohol'],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
  },
  {
    id: '6',
    name: 'Burrata & Heirloom',
    description: 'Creamy burrata, balsamic pearls, heritage tomatoes.',
    price: 26,
    category: 'Appetizers',
    image: 'https://images.unsplash.com/photo-1592417817098-8fd3d0f419d1?auto=format&fit=crop&q=80&w=800',
    nutritionalInfo: { calories: 310, protein: '12g', fat: '24g' },
    allergens: ['Dairy'],
    isVegetarian: true,
    isGlutenFree: true,
  },
  {
    id: '7',
    name: 'Garden Fresh Salad',
    description: 'Organic greens, radishes, carrots, house vinaigrette.',
    price: 18,
    category: 'Appetizers',
    image: 'https://images.unsplash.com/photo-1540420753440-4ad098472111?auto=format&fit=crop&q=80&w=800',
    nutritionalInfo: { calories: 120, protein: '2g', fat: '8g' },
    allergens: [],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
  },
];
